//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAnArtisanMVC.ProjectServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Contact_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Created_by_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Project_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Project_status_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Start_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact_ID {
            get {
                return this.Contact_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Contact_IDField, value) != true)) {
                    this.Contact_IDField = value;
                    this.RaisePropertyChanged("Contact_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Created_by_ID {
            get {
                return this.Created_by_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Created_by_IDField, value) != true)) {
                    this.Created_by_IDField = value;
                    this.RaisePropertyChanged("Created_by_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Project_description {
            get {
                return this.Project_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Project_descriptionField, value) != true)) {
                    this.Project_descriptionField = value;
                    this.RaisePropertyChanged("Project_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Project_status_ID {
            get {
                return this.Project_status_IDField;
            }
            set {
                if ((this.Project_status_IDField.Equals(value) != true)) {
                    this.Project_status_IDField = value;
                    this.RaisePropertyChanged("Project_status_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start_time {
            get {
                return this.Start_timeField;
            }
            set {
                if ((this.Start_timeField.Equals(value) != true)) {
                    this.Start_timeField = value;
                    this.RaisePropertyChanged("Start_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street_Name {
            get {
                return this.Street_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Street_NameField, value) != true)) {
                    this.Street_NameField = value;
                    this.RaisePropertyChanged("Street_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProjectServiceReference.IProjectService")]
    public interface IProjectService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Project/Create", ReplyAction="http://tempuri.org/IServiceOf_Project/CreateResponse")]
        BookAnArtisanMVC.ProjectServiceReference.Project Create(BookAnArtisanMVC.ProjectServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Project/Create", ReplyAction="http://tempuri.org/IServiceOf_Project/CreateResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ProjectServiceReference.Project> CreateAsync(BookAnArtisanMVC.ProjectServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Project/Read", ReplyAction="http://tempuri.org/IServiceOf_Project/ReadResponse")]
        BookAnArtisanMVC.ProjectServiceReference.Project Read(BookAnArtisanMVC.ProjectServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Project/Read", ReplyAction="http://tempuri.org/IServiceOf_Project/ReadResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ProjectServiceReference.Project> ReadAsync(BookAnArtisanMVC.ProjectServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Project/Update", ReplyAction="http://tempuri.org/IServiceOf_Project/UpdateResponse")]
        BookAnArtisanMVC.ProjectServiceReference.Project Update(BookAnArtisanMVC.ProjectServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Project/Update", ReplyAction="http://tempuri.org/IServiceOf_Project/UpdateResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ProjectServiceReference.Project> UpdateAsync(BookAnArtisanMVC.ProjectServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Project/Delete", ReplyAction="http://tempuri.org/IServiceOf_Project/DeleteResponse")]
        BookAnArtisanMVC.ProjectServiceReference.Project Delete(BookAnArtisanMVC.ProjectServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Project/Delete", ReplyAction="http://tempuri.org/IServiceOf_Project/DeleteResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ProjectServiceReference.Project> DeleteAsync(BookAnArtisanMVC.ProjectServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Project/ReadAll", ReplyAction="http://tempuri.org/IServiceOf_Project/ReadAllResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ProjectServiceReference.Project> ReadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Project/ReadAll", ReplyAction="http://tempuri.org/IServiceOf_Project/ReadAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ProjectServiceReference.Project>> ReadAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectServiceChannel : BookAnArtisanMVC.ProjectServiceReference.IProjectService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectServiceClient : System.ServiceModel.ClientBase<BookAnArtisanMVC.ProjectServiceReference.IProjectService>, BookAnArtisanMVC.ProjectServiceReference.IProjectService {
        
        public ProjectServiceClient() {
        }
        
        public ProjectServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookAnArtisanMVC.ProjectServiceReference.Project Create(BookAnArtisanMVC.ProjectServiceReference.Project t) {
            return base.Channel.Create(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ProjectServiceReference.Project> CreateAsync(BookAnArtisanMVC.ProjectServiceReference.Project t) {
            return base.Channel.CreateAsync(t);
        }
        
        public BookAnArtisanMVC.ProjectServiceReference.Project Read(BookAnArtisanMVC.ProjectServiceReference.Project t) {
            return base.Channel.Read(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ProjectServiceReference.Project> ReadAsync(BookAnArtisanMVC.ProjectServiceReference.Project t) {
            return base.Channel.ReadAsync(t);
        }
        
        public BookAnArtisanMVC.ProjectServiceReference.Project Update(BookAnArtisanMVC.ProjectServiceReference.Project t) {
            return base.Channel.Update(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ProjectServiceReference.Project> UpdateAsync(BookAnArtisanMVC.ProjectServiceReference.Project t) {
            return base.Channel.UpdateAsync(t);
        }
        
        public BookAnArtisanMVC.ProjectServiceReference.Project Delete(BookAnArtisanMVC.ProjectServiceReference.Project t) {
            return base.Channel.Delete(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ProjectServiceReference.Project> DeleteAsync(BookAnArtisanMVC.ProjectServiceReference.Project t) {
            return base.Channel.DeleteAsync(t);
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ProjectServiceReference.Project> ReadAll() {
            return base.Channel.ReadAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ProjectServiceReference.Project>> ReadAllAsync() {
            return base.Channel.ReadAllAsync();
        }
    }
}
