//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApactaWPF.ServiceReferences {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccessFailedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApiKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockoutEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LockoutEndDateUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PhoneNumberConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TwoFactorEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccessFailedCount {
            get {
                return this.AccessFailedCountField;
            }
            set {
                if ((this.AccessFailedCountField.Equals(value) != true)) {
                    this.AccessFailedCountField = value;
                    this.RaisePropertyChanged("AccessFailedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApiKey {
            get {
                return this.ApiKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ApiKeyField, value) != true)) {
                    this.ApiKeyField = value;
                    this.RaisePropertyChanged("ApiKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailConfirmed {
            get {
                return this.EmailConfirmedField;
            }
            set {
                if ((this.EmailConfirmedField.Equals(value) != true)) {
                    this.EmailConfirmedField = value;
                    this.RaisePropertyChanged("EmailConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LockoutEnabled {
            get {
                return this.LockoutEnabledField;
            }
            set {
                if ((this.LockoutEnabledField.Equals(value) != true)) {
                    this.LockoutEnabledField = value;
                    this.RaisePropertyChanged("LockoutEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LockoutEndDateUtc {
            get {
                return this.LockoutEndDateUtcField;
            }
            set {
                if ((this.LockoutEndDateUtcField.Equals(value) != true)) {
                    this.LockoutEndDateUtcField = value;
                    this.RaisePropertyChanged("LockoutEndDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PhoneNumberConfirmed {
            get {
                return this.PhoneNumberConfirmedField;
            }
            set {
                if ((this.PhoneNumberConfirmedField.Equals(value) != true)) {
                    this.PhoneNumberConfirmedField = value;
                    this.RaisePropertyChanged("PhoneNumberConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityStamp {
            get {
                return this.SecurityStampField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityStampField, value) != true)) {
                    this.SecurityStampField = value;
                    this.RaisePropertyChanged("SecurityStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TwoFactorEnabled {
            get {
                return this.TwoFactorEnabledField;
            }
            set {
                if ((this.TwoFactorEnabledField.Equals(value) != true)) {
                    this.TwoFactorEnabledField = value;
                    this.RaisePropertyChanged("TwoFactorEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApactaWPF.ServiceReferences.User OwnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((this.AvailableField.Equals(value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionField, value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApactaWPF.ServiceReferences.User Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageOfMaterialYgFqSxnr", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class PageOfMaterialYgFqSxnr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApactaWPF.ServiceReferences.Material[] PageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndPage {
            get {
                return this.EndPageField;
            }
            set {
                if ((this.EndPageField.Equals(value) != true)) {
                    this.EndPageField = value;
                    this.RaisePropertyChanged("EndPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApactaWPF.ServiceReferences.Material[] PageList {
            get {
                return this.PageListField;
            }
            set {
                if ((object.ReferenceEquals(this.PageListField, value) != true)) {
                    this.PageListField = value;
                    this.RaisePropertyChanged("PageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartPage {
            get {
                return this.StartPageField;
            }
            set {
                if ((this.StartPageField.Equals(value) != true)) {
                    this.StartPageField = value;
                    this.RaisePropertyChanged("StartPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApactaWPF.ServiceReferences.Material ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApactaWPF.ServiceReferences.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApactaWPF.ServiceReferences.Material Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Updated {
            get {
                return this.UpdatedField;
            }
            set {
                if ((this.UpdatedField.Equals(value) != true)) {
                    this.UpdatedField = value;
                    this.RaisePropertyChanged("Updated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApactaWPF.ServiceReferences.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferences.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateUser", ReplyAction="http://tempuri.org/IUserService/CreateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IUserService/CreateUserApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.User CreateUser(ApactaWPF.ServiceReferences.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateUser", ReplyAction="http://tempuri.org/IUserService/CreateUserResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User> CreateUserAsync(ApactaWPF.ServiceReferences.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ReadUser", ReplyAction="http://tempuri.org/IUserService/ReadUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IUserService/ReadUserApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.User ReadUser(ApactaWPF.ServiceReferences.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ReadUser", ReplyAction="http://tempuri.org/IUserService/ReadUserResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User> ReadUserAsync(ApactaWPF.ServiceReferences.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IUserService/UpdateUserApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.User UpdateUser(ApactaWPF.ServiceReferences.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User> UpdateUserAsync(ApactaWPF.ServiceReferences.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IUserService/DeleteUserApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.User DeleteUser(ApactaWPF.ServiceReferences.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User> DeleteUserAsync(ApactaWPF.ServiceReferences.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ReadAllUser", ReplyAction="http://tempuri.org/IUserService/ReadAllUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IUserService/ReadAllUserApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.User[] ReadAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ReadAllUser", ReplyAction="http://tempuri.org/IUserService/ReadAllUserResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User[]> ReadAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchByName", ReplyAction="http://tempuri.org/IUserService/SearchByNameResponse")]
        ApactaWPF.ServiceReferences.User[] SearchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchByName", ReplyAction="http://tempuri.org/IUserService/SearchByNameResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User[]> SearchByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : ApactaWPF.ServiceReferences.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<ApactaWPF.ServiceReferences.IUserService>, ApactaWPF.ServiceReferences.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApactaWPF.ServiceReferences.User CreateUser(ApactaWPF.ServiceReferences.User t) {
            return base.Channel.CreateUser(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User> CreateUserAsync(ApactaWPF.ServiceReferences.User t) {
            return base.Channel.CreateUserAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.User ReadUser(ApactaWPF.ServiceReferences.User t) {
            return base.Channel.ReadUser(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User> ReadUserAsync(ApactaWPF.ServiceReferences.User t) {
            return base.Channel.ReadUserAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.User UpdateUser(ApactaWPF.ServiceReferences.User t) {
            return base.Channel.UpdateUser(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User> UpdateUserAsync(ApactaWPF.ServiceReferences.User t) {
            return base.Channel.UpdateUserAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.User DeleteUser(ApactaWPF.ServiceReferences.User t) {
            return base.Channel.DeleteUser(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User> DeleteUserAsync(ApactaWPF.ServiceReferences.User t) {
            return base.Channel.DeleteUserAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.User[] ReadAllUser() {
            return base.Channel.ReadAllUser();
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User[]> ReadAllUserAsync() {
            return base.Channel.ReadAllUserAsync();
        }
        
        public ApactaWPF.ServiceReferences.User[] SearchByName(string name) {
            return base.Channel.SearchByName(name);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.User[]> SearchByNameAsync(string name) {
            return base.Channel.SearchByNameAsync(name);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferences.IMaterialService")]
    public interface IMaterialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/CreateMaterial", ReplyAction="http://tempuri.org/IMaterialService/CreateMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IMaterialService/CreateMaterialApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Material CreateMaterial(ApactaWPF.ServiceReferences.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/CreateMaterial", ReplyAction="http://tempuri.org/IMaterialService/CreateMaterialResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material> CreateMaterialAsync(ApactaWPF.ServiceReferences.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadMaterial", ReplyAction="http://tempuri.org/IMaterialService/ReadMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IMaterialService/ReadMaterialApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Material ReadMaterial(ApactaWPF.ServiceReferences.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadMaterial", ReplyAction="http://tempuri.org/IMaterialService/ReadMaterialResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material> ReadMaterialAsync(ApactaWPF.ServiceReferences.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/UpdateMaterial", ReplyAction="http://tempuri.org/IMaterialService/UpdateMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IMaterialService/UpdateMaterialApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Material UpdateMaterial(ApactaWPF.ServiceReferences.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/UpdateMaterial", ReplyAction="http://tempuri.org/IMaterialService/UpdateMaterialResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material> UpdateMaterialAsync(ApactaWPF.ServiceReferences.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/DeleteMaterial", ReplyAction="http://tempuri.org/IMaterialService/DeleteMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IMaterialService/DeleteMaterialApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Material DeleteMaterial(ApactaWPF.ServiceReferences.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/DeleteMaterial", ReplyAction="http://tempuri.org/IMaterialService/DeleteMaterialResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material> DeleteMaterialAsync(ApactaWPF.ServiceReferences.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadAllMaterial", ReplyAction="http://tempuri.org/IMaterialService/ReadAllMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IMaterialService/ReadAllMaterialApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Material[] ReadAllMaterial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadAllMaterial", ReplyAction="http://tempuri.org/IMaterialService/ReadAllMaterialResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material[]> ReadAllMaterialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/Search", ReplyAction="http://tempuri.org/IMaterialService/SearchResponse")]
        ApactaWPF.ServiceReferences.Material[] Search(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/Search", ReplyAction="http://tempuri.org/IMaterialService/SearchResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material[]> SearchAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadAllMaterialsForUser", ReplyAction="http://tempuri.org/IMaterialService/ReadAllMaterialsForUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IMaterialService/ReadAllMaterialsForUserApplicationExceptionFa" +
            "ult", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Material[] ReadAllMaterialsForUser(ApactaWPF.ServiceReferences.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadAllMaterialsForUser", ReplyAction="http://tempuri.org/IMaterialService/ReadAllMaterialsForUserResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material[]> ReadAllMaterialsForUserAsync(ApactaWPF.ServiceReferences.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadPage", ReplyAction="http://tempuri.org/IMaterialService/ReadPageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IMaterialService/ReadPageApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr ReadPage(System.Nullable<int> page, System.Nullable<int> pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadPage", ReplyAction="http://tempuri.org/IMaterialService/ReadPageResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr> ReadPageAsync(System.Nullable<int> page, System.Nullable<int> pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadPageForUser", ReplyAction="http://tempuri.org/IMaterialService/ReadPageForUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IMaterialService/ReadPageForUserApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr ReadPageForUser(System.Nullable<int> page, System.Nullable<int> pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadPageForUser", ReplyAction="http://tempuri.org/IMaterialService/ReadPageForUserResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr> ReadPageForUserAsync(System.Nullable<int> page, System.Nullable<int> pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaterialServiceChannel : ApactaWPF.ServiceReferences.IMaterialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialServiceClient : System.ServiceModel.ClientBase<ApactaWPF.ServiceReferences.IMaterialService>, ApactaWPF.ServiceReferences.IMaterialService {
        
        public MaterialServiceClient() {
        }
        
        public MaterialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApactaWPF.ServiceReferences.Material CreateMaterial(ApactaWPF.ServiceReferences.Material t) {
            return base.Channel.CreateMaterial(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material> CreateMaterialAsync(ApactaWPF.ServiceReferences.Material t) {
            return base.Channel.CreateMaterialAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.Material ReadMaterial(ApactaWPF.ServiceReferences.Material t) {
            return base.Channel.ReadMaterial(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material> ReadMaterialAsync(ApactaWPF.ServiceReferences.Material t) {
            return base.Channel.ReadMaterialAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.Material UpdateMaterial(ApactaWPF.ServiceReferences.Material t) {
            return base.Channel.UpdateMaterial(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material> UpdateMaterialAsync(ApactaWPF.ServiceReferences.Material t) {
            return base.Channel.UpdateMaterialAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.Material DeleteMaterial(ApactaWPF.ServiceReferences.Material t) {
            return base.Channel.DeleteMaterial(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material> DeleteMaterialAsync(ApactaWPF.ServiceReferences.Material t) {
            return base.Channel.DeleteMaterialAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.Material[] ReadAllMaterial() {
            return base.Channel.ReadAllMaterial();
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material[]> ReadAllMaterialAsync() {
            return base.Channel.ReadAllMaterialAsync();
        }
        
        public ApactaWPF.ServiceReferences.Material[] Search(string name) {
            return base.Channel.Search(name);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material[]> SearchAsync(string name) {
            return base.Channel.SearchAsync(name);
        }
        
        public ApactaWPF.ServiceReferences.Material[] ReadAllMaterialsForUser(ApactaWPF.ServiceReferences.User user) {
            return base.Channel.ReadAllMaterialsForUser(user);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Material[]> ReadAllMaterialsForUserAsync(ApactaWPF.ServiceReferences.User user) {
            return base.Channel.ReadAllMaterialsForUserAsync(user);
        }
        
        public ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr ReadPage(System.Nullable<int> page, System.Nullable<int> pageSize) {
            return base.Channel.ReadPage(page, pageSize);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr> ReadPageAsync(System.Nullable<int> page, System.Nullable<int> pageSize) {
            return base.Channel.ReadPageAsync(page, pageSize);
        }
        
        public ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr ReadPageForUser(System.Nullable<int> page, System.Nullable<int> pageSize) {
            return base.Channel.ReadPageForUser(page, pageSize);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr> ReadPageForUserAsync(System.Nullable<int> page, System.Nullable<int> pageSize) {
            return base.Channel.ReadPageForUserAsync(page, pageSize);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferences.IBookingService")]
    public interface IBookingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/CreateBooking", ReplyAction="http://tempuri.org/IBookingService/CreateBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IBookingService/CreateBookingApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Booking CreateBooking(ApactaWPF.ServiceReferences.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/CreateBooking", ReplyAction="http://tempuri.org/IBookingService/CreateBookingResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Booking> CreateBookingAsync(ApactaWPF.ServiceReferences.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/ReadBooking", ReplyAction="http://tempuri.org/IBookingService/ReadBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IBookingService/ReadBookingApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Booking ReadBooking(ApactaWPF.ServiceReferences.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/ReadBooking", ReplyAction="http://tempuri.org/IBookingService/ReadBookingResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Booking> ReadBookingAsync(ApactaWPF.ServiceReferences.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/UpdateBooking", ReplyAction="http://tempuri.org/IBookingService/UpdateBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IBookingService/UpdateBookingApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Booking UpdateBooking(ApactaWPF.ServiceReferences.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/UpdateBooking", ReplyAction="http://tempuri.org/IBookingService/UpdateBookingResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Booking> UpdateBookingAsync(ApactaWPF.ServiceReferences.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/DeleteBooking", ReplyAction="http://tempuri.org/IBookingService/DeleteBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IBookingService/DeleteBookingApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Booking DeleteBooking(ApactaWPF.ServiceReferences.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/DeleteBooking", ReplyAction="http://tempuri.org/IBookingService/DeleteBookingResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Booking> DeleteBookingAsync(ApactaWPF.ServiceReferences.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/ReadAllBooking", ReplyAction="http://tempuri.org/IBookingService/ReadAllBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IBookingService/ReadAllBookingApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.Booking[] ReadAllBooking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/ReadAllBooking", ReplyAction="http://tempuri.org/IBookingService/ReadAllBookingResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Booking[]> ReadAllBookingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/ReadPage", ReplyAction="http://tempuri.org/IBookingService/ReadPageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IBookingService/ReadPageApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr ReadPage(System.Nullable<int> page, System.Nullable<int> pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/ReadPage", ReplyAction="http://tempuri.org/IBookingService/ReadPageResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr> ReadPageAsync(System.Nullable<int> page, System.Nullable<int> pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/ReadPageForUser", ReplyAction="http://tempuri.org/IBookingService/ReadPageForUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ApplicationException), Action="http://tempuri.org/IBookingService/ReadPageForUserApplicationExceptionFault", Name="ApplicationException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr ReadPageForUser(System.Nullable<int> page, System.Nullable<int> pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/ReadPageForUser", ReplyAction="http://tempuri.org/IBookingService/ReadPageForUserResponse")]
        System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr> ReadPageForUserAsync(System.Nullable<int> page, System.Nullable<int> pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookingServiceChannel : ApactaWPF.ServiceReferences.IBookingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingServiceClient : System.ServiceModel.ClientBase<ApactaWPF.ServiceReferences.IBookingService>, ApactaWPF.ServiceReferences.IBookingService {
        
        public BookingServiceClient() {
        }
        
        public BookingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApactaWPF.ServiceReferences.Booking CreateBooking(ApactaWPF.ServiceReferences.Booking t) {
            return base.Channel.CreateBooking(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Booking> CreateBookingAsync(ApactaWPF.ServiceReferences.Booking t) {
            return base.Channel.CreateBookingAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.Booking ReadBooking(ApactaWPF.ServiceReferences.Booking t) {
            return base.Channel.ReadBooking(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Booking> ReadBookingAsync(ApactaWPF.ServiceReferences.Booking t) {
            return base.Channel.ReadBookingAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.Booking UpdateBooking(ApactaWPF.ServiceReferences.Booking t) {
            return base.Channel.UpdateBooking(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Booking> UpdateBookingAsync(ApactaWPF.ServiceReferences.Booking t) {
            return base.Channel.UpdateBookingAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.Booking DeleteBooking(ApactaWPF.ServiceReferences.Booking t) {
            return base.Channel.DeleteBooking(t);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Booking> DeleteBookingAsync(ApactaWPF.ServiceReferences.Booking t) {
            return base.Channel.DeleteBookingAsync(t);
        }
        
        public ApactaWPF.ServiceReferences.Booking[] ReadAllBooking() {
            return base.Channel.ReadAllBooking();
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.Booking[]> ReadAllBookingAsync() {
            return base.Channel.ReadAllBookingAsync();
        }
        
        public ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr ReadPage(System.Nullable<int> page, System.Nullable<int> pageSize) {
            return base.Channel.ReadPage(page, pageSize);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr> ReadPageAsync(System.Nullable<int> page, System.Nullable<int> pageSize) {
            return base.Channel.ReadPageAsync(page, pageSize);
        }
        
        public ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr ReadPageForUser(System.Nullable<int> page, System.Nullable<int> pageSize) {
            return base.Channel.ReadPageForUser(page, pageSize);
        }
        
        public System.Threading.Tasks.Task<ApactaWPF.ServiceReferences.PageOfMaterialYgFqSxnr> ReadPageForUserAsync(System.Nullable<int> page, System.Nullable<int> pageSize) {
            return base.Channel.ReadPageForUserAsync(page, pageSize);
        }
    }
}
