//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAnArtisanMVC.MeetingServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Meeting", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Meeting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactId {
            get {
                return this.ContactIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactIdField, value) != true)) {
                    this.ContactIdField = value;
                    this.RaisePropertyChanged("ContactId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedById {
            get {
                return this.CreatedByIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByIdField, value) != true)) {
                    this.CreatedByIdField = value;
                    this.RaisePropertyChanged("CreatedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MeetingServiceReference.IMeetingService")]
    public interface IMeetingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Meeting/Create", ReplyAction="http://tempuri.org/IServiceOf_Meeting/CreateResponse")]
        BookAnArtisanMVC.MeetingServiceReference.Meeting Create(BookAnArtisanMVC.MeetingServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Meeting/Create", ReplyAction="http://tempuri.org/IServiceOf_Meeting/CreateResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.MeetingServiceReference.Meeting> CreateAsync(BookAnArtisanMVC.MeetingServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Meeting/Read", ReplyAction="http://tempuri.org/IServiceOf_Meeting/ReadResponse")]
        BookAnArtisanMVC.MeetingServiceReference.Meeting Read(BookAnArtisanMVC.MeetingServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Meeting/Read", ReplyAction="http://tempuri.org/IServiceOf_Meeting/ReadResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.MeetingServiceReference.Meeting> ReadAsync(BookAnArtisanMVC.MeetingServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Meeting/Update", ReplyAction="http://tempuri.org/IServiceOf_Meeting/UpdateResponse")]
        BookAnArtisanMVC.MeetingServiceReference.Meeting Update(BookAnArtisanMVC.MeetingServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Meeting/Update", ReplyAction="http://tempuri.org/IServiceOf_Meeting/UpdateResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.MeetingServiceReference.Meeting> UpdateAsync(BookAnArtisanMVC.MeetingServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Meeting/Delete", ReplyAction="http://tempuri.org/IServiceOf_Meeting/DeleteResponse")]
        bool Delete(BookAnArtisanMVC.MeetingServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Meeting/Delete", ReplyAction="http://tempuri.org/IServiceOf_Meeting/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(BookAnArtisanMVC.MeetingServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Meeting/ReadAll", ReplyAction="http://tempuri.org/IServiceOf_Meeting/ReadAllResponse")]
        BookAnArtisanMVC.MeetingServiceReference.Meeting[] ReadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_Meeting/ReadAll", ReplyAction="http://tempuri.org/IServiceOf_Meeting/ReadAllResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.MeetingServiceReference.Meeting[]> ReadAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMeetingServiceChannel : BookAnArtisanMVC.MeetingServiceReference.IMeetingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeetingServiceClient : System.ServiceModel.ClientBase<BookAnArtisanMVC.MeetingServiceReference.IMeetingService>, BookAnArtisanMVC.MeetingServiceReference.IMeetingService {
        
        public MeetingServiceClient() {
        }
        
        public MeetingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeetingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeetingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeetingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookAnArtisanMVC.MeetingServiceReference.Meeting Create(BookAnArtisanMVC.MeetingServiceReference.Meeting t) {
            return base.Channel.Create(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.MeetingServiceReference.Meeting> CreateAsync(BookAnArtisanMVC.MeetingServiceReference.Meeting t) {
            return base.Channel.CreateAsync(t);
        }
        
        public BookAnArtisanMVC.MeetingServiceReference.Meeting Read(BookAnArtisanMVC.MeetingServiceReference.Meeting t) {
            return base.Channel.Read(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.MeetingServiceReference.Meeting> ReadAsync(BookAnArtisanMVC.MeetingServiceReference.Meeting t) {
            return base.Channel.ReadAsync(t);
        }
        
        public BookAnArtisanMVC.MeetingServiceReference.Meeting Update(BookAnArtisanMVC.MeetingServiceReference.Meeting t) {
            return base.Channel.Update(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.MeetingServiceReference.Meeting> UpdateAsync(BookAnArtisanMVC.MeetingServiceReference.Meeting t) {
            return base.Channel.UpdateAsync(t);
        }
        
        public bool Delete(BookAnArtisanMVC.MeetingServiceReference.Meeting t) {
            return base.Channel.Delete(t);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(BookAnArtisanMVC.MeetingServiceReference.Meeting t) {
            return base.Channel.DeleteAsync(t);
        }
        
        public BookAnArtisanMVC.MeetingServiceReference.Meeting[] ReadAll() {
            return base.Channel.ReadAll();
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.MeetingServiceReference.Meeting[]> ReadAllAsync() {
            return base.Channel.ReadAllAsync();
        }
    }
}
