//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAnArtisanMVC.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookAnArtisanMVC.ServiceReference.User OwnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Available {
            get {
                return this.AvailableField;
            }
            set {
                if ((this.AvailableField.Equals(value) != true)) {
                    this.AvailableField = value;
                    this.RaisePropertyChanged("Available");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionField, value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookAnArtisanMVC.ServiceReference.User Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccessFailedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApiKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockoutEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LockoutEndDateUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PhoneNumberConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TwoFactorEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccessFailedCount {
            get {
                return this.AccessFailedCountField;
            }
            set {
                if ((this.AccessFailedCountField.Equals(value) != true)) {
                    this.AccessFailedCountField = value;
                    this.RaisePropertyChanged("AccessFailedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApiKey {
            get {
                return this.ApiKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ApiKeyField, value) != true)) {
                    this.ApiKeyField = value;
                    this.RaisePropertyChanged("ApiKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailConfirmed {
            get {
                return this.EmailConfirmedField;
            }
            set {
                if ((this.EmailConfirmedField.Equals(value) != true)) {
                    this.EmailConfirmedField = value;
                    this.RaisePropertyChanged("EmailConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LockoutEnabled {
            get {
                return this.LockoutEnabledField;
            }
            set {
                if ((this.LockoutEnabledField.Equals(value) != true)) {
                    this.LockoutEnabledField = value;
                    this.RaisePropertyChanged("LockoutEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LockoutEndDateUtc {
            get {
                return this.LockoutEndDateUtcField;
            }
            set {
                if ((this.LockoutEndDateUtcField.Equals(value) != true)) {
                    this.LockoutEndDateUtcField = value;
                    this.RaisePropertyChanged("LockoutEndDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PhoneNumberConfirmed {
            get {
                return this.PhoneNumberConfirmedField;
            }
            set {
                if ((this.PhoneNumberConfirmedField.Equals(value) != true)) {
                    this.PhoneNumberConfirmedField = value;
                    this.RaisePropertyChanged("PhoneNumberConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityStamp {
            get {
                return this.SecurityStampField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityStampField, value) != true)) {
                    this.SecurityStampField = value;
                    this.RaisePropertyChanged("SecurityStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TwoFactorEnabled {
            get {
                return this.TwoFactorEnabledField;
            }
            set {
                if ((this.TwoFactorEnabledField.Equals(value) != true)) {
                    this.TwoFactorEnabledField = value;
                    this.RaisePropertyChanged("TwoFactorEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Meeting", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Meeting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookAnArtisanMVC.ServiceReference.User ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookAnArtisanMVC.ServiceReference.User CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookAnArtisanMVC.ServiceReference.User Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookAnArtisanMVC.ServiceReference.User CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookAnArtisanMVC.ServiceReference.User ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookAnArtisanMVC.ServiceReference.User CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectStatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookAnArtisanMVC.ServiceReference.User Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookAnArtisanMVC.ServiceReference.User CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectDescription {
            get {
                return this.ProjectDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectDescriptionField, value) != true)) {
                    this.ProjectDescriptionField = value;
                    this.RaisePropertyChanged("ProjectDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectStatusID {
            get {
                return this.ProjectStatusIDField;
            }
            set {
                if ((this.ProjectStatusIDField.Equals(value) != true)) {
                    this.ProjectStatusIDField = value;
                    this.RaisePropertyChanged("ProjectStatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName {
            get {
                return this.StreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNameField, value) != true)) {
                    this.StreetNameField = value;
                    this.RaisePropertyChanged("StreetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookAnArtisanMVC.ServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookAnArtisanMVC.ServiceReference.Material itemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookAnArtisanMVC.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookAnArtisanMVC.ServiceReference.Material item {
            get {
                return this.itemField;
            }
            set {
                if ((object.ReferenceEquals(this.itemField, value) != true)) {
                    this.itemField = value;
                    this.RaisePropertyChanged("item");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IMaterialService")]
    public interface IMaterialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/CreateMaterial", ReplyAction="http://tempuri.org/IMaterialService/CreateMaterialResponse")]
        BookAnArtisanMVC.ServiceReference.Material CreateMaterial(BookAnArtisanMVC.ServiceReference.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/CreateMaterial", ReplyAction="http://tempuri.org/IMaterialService/CreateMaterialResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Material> CreateMaterialAsync(BookAnArtisanMVC.ServiceReference.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadMaterial", ReplyAction="http://tempuri.org/IMaterialService/ReadMaterialResponse")]
        BookAnArtisanMVC.ServiceReference.Material ReadMaterial(BookAnArtisanMVC.ServiceReference.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadMaterial", ReplyAction="http://tempuri.org/IMaterialService/ReadMaterialResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Material> ReadMaterialAsync(BookAnArtisanMVC.ServiceReference.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/UpdateMaterial", ReplyAction="http://tempuri.org/IMaterialService/UpdateMaterialResponse")]
        BookAnArtisanMVC.ServiceReference.Material UpdateMaterial(BookAnArtisanMVC.ServiceReference.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/UpdateMaterial", ReplyAction="http://tempuri.org/IMaterialService/UpdateMaterialResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Material> UpdateMaterialAsync(BookAnArtisanMVC.ServiceReference.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/DeleteMaterial", ReplyAction="http://tempuri.org/IMaterialService/DeleteMaterialResponse")]
        BookAnArtisanMVC.ServiceReference.Material DeleteMaterial(BookAnArtisanMVC.ServiceReference.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/DeleteMaterial", ReplyAction="http://tempuri.org/IMaterialService/DeleteMaterialResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Material> DeleteMaterialAsync(BookAnArtisanMVC.ServiceReference.Material t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadAllMaterial", ReplyAction="http://tempuri.org/IMaterialService/ReadAllMaterialResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Material> ReadAllMaterial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/ReadAllMaterial", ReplyAction="http://tempuri.org/IMaterialService/ReadAllMaterialResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Material>> ReadAllMaterialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/Search", ReplyAction="http://tempuri.org/IMaterialService/SearchResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Material> Search(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaterialService/Search", ReplyAction="http://tempuri.org/IMaterialService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Material>> SearchAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaterialServiceChannel : BookAnArtisanMVC.ServiceReference.IMaterialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialServiceClient : System.ServiceModel.ClientBase<BookAnArtisanMVC.ServiceReference.IMaterialService>, BookAnArtisanMVC.ServiceReference.IMaterialService {
        
        public MaterialServiceClient() {
        }
        
        public MaterialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookAnArtisanMVC.ServiceReference.Material CreateMaterial(BookAnArtisanMVC.ServiceReference.Material t) {
            return base.Channel.CreateMaterial(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Material> CreateMaterialAsync(BookAnArtisanMVC.ServiceReference.Material t) {
            return base.Channel.CreateMaterialAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Material ReadMaterial(BookAnArtisanMVC.ServiceReference.Material t) {
            return base.Channel.ReadMaterial(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Material> ReadMaterialAsync(BookAnArtisanMVC.ServiceReference.Material t) {
            return base.Channel.ReadMaterialAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Material UpdateMaterial(BookAnArtisanMVC.ServiceReference.Material t) {
            return base.Channel.UpdateMaterial(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Material> UpdateMaterialAsync(BookAnArtisanMVC.ServiceReference.Material t) {
            return base.Channel.UpdateMaterialAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Material DeleteMaterial(BookAnArtisanMVC.ServiceReference.Material t) {
            return base.Channel.DeleteMaterial(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Material> DeleteMaterialAsync(BookAnArtisanMVC.ServiceReference.Material t) {
            return base.Channel.DeleteMaterialAsync(t);
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Material> ReadAllMaterial() {
            return base.Channel.ReadAllMaterial();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Material>> ReadAllMaterialAsync() {
            return base.Channel.ReadAllMaterialAsync();
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Material> Search(string name) {
            return base.Channel.Search(name);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Material>> SearchAsync(string name) {
            return base.Channel.SearchAsync(name);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IMeetingService")]
    public interface IMeetingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/CreateMeeting", ReplyAction="http://tempuri.org/IMeetingService/CreateMeetingResponse")]
        BookAnArtisanMVC.ServiceReference.Meeting CreateMeeting(BookAnArtisanMVC.ServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/CreateMeeting", ReplyAction="http://tempuri.org/IMeetingService/CreateMeetingResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Meeting> CreateMeetingAsync(BookAnArtisanMVC.ServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/ReadMeeting", ReplyAction="http://tempuri.org/IMeetingService/ReadMeetingResponse")]
        BookAnArtisanMVC.ServiceReference.Meeting ReadMeeting(BookAnArtisanMVC.ServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/ReadMeeting", ReplyAction="http://tempuri.org/IMeetingService/ReadMeetingResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Meeting> ReadMeetingAsync(BookAnArtisanMVC.ServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/UpdateMeeting", ReplyAction="http://tempuri.org/IMeetingService/UpdateMeetingResponse")]
        BookAnArtisanMVC.ServiceReference.Meeting UpdateMeeting(BookAnArtisanMVC.ServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/UpdateMeeting", ReplyAction="http://tempuri.org/IMeetingService/UpdateMeetingResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Meeting> UpdateMeetingAsync(BookAnArtisanMVC.ServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/DeleteMeeting", ReplyAction="http://tempuri.org/IMeetingService/DeleteMeetingResponse")]
        BookAnArtisanMVC.ServiceReference.Meeting DeleteMeeting(BookAnArtisanMVC.ServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/DeleteMeeting", ReplyAction="http://tempuri.org/IMeetingService/DeleteMeetingResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Meeting> DeleteMeetingAsync(BookAnArtisanMVC.ServiceReference.Meeting t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/ReadAllMeeting", ReplyAction="http://tempuri.org/IMeetingService/ReadAllMeetingResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Meeting> ReadAllMeeting();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/ReadAllMeeting", ReplyAction="http://tempuri.org/IMeetingService/ReadAllMeetingResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Meeting>> ReadAllMeetingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/AddUserToMeeting", ReplyAction="http://tempuri.org/IMeetingService/AddUserToMeetingResponse")]
        BookAnArtisanMVC.ServiceReference.Meeting AddUserToMeeting(BookAnArtisanMVC.ServiceReference.Meeting m, BookAnArtisanMVC.ServiceReference.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/AddUserToMeeting", ReplyAction="http://tempuri.org/IMeetingService/AddUserToMeetingResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Meeting> AddUserToMeetingAsync(BookAnArtisanMVC.ServiceReference.Meeting m, BookAnArtisanMVC.ServiceReference.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/ReadAllForUser", ReplyAction="http://tempuri.org/IMeetingService/ReadAllForUserResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Meeting> ReadAllForUser(BookAnArtisanMVC.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeetingService/ReadAllForUser", ReplyAction="http://tempuri.org/IMeetingService/ReadAllForUserResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Meeting>> ReadAllForUserAsync(BookAnArtisanMVC.ServiceReference.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMeetingServiceChannel : BookAnArtisanMVC.ServiceReference.IMeetingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeetingServiceClient : System.ServiceModel.ClientBase<BookAnArtisanMVC.ServiceReference.IMeetingService>, BookAnArtisanMVC.ServiceReference.IMeetingService {
        
        public MeetingServiceClient() {
        }
        
        public MeetingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeetingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeetingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeetingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookAnArtisanMVC.ServiceReference.Meeting CreateMeeting(BookAnArtisanMVC.ServiceReference.Meeting t) {
            return base.Channel.CreateMeeting(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Meeting> CreateMeetingAsync(BookAnArtisanMVC.ServiceReference.Meeting t) {
            return base.Channel.CreateMeetingAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Meeting ReadMeeting(BookAnArtisanMVC.ServiceReference.Meeting t) {
            return base.Channel.ReadMeeting(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Meeting> ReadMeetingAsync(BookAnArtisanMVC.ServiceReference.Meeting t) {
            return base.Channel.ReadMeetingAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Meeting UpdateMeeting(BookAnArtisanMVC.ServiceReference.Meeting t) {
            return base.Channel.UpdateMeeting(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Meeting> UpdateMeetingAsync(BookAnArtisanMVC.ServiceReference.Meeting t) {
            return base.Channel.UpdateMeetingAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Meeting DeleteMeeting(BookAnArtisanMVC.ServiceReference.Meeting t) {
            return base.Channel.DeleteMeeting(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Meeting> DeleteMeetingAsync(BookAnArtisanMVC.ServiceReference.Meeting t) {
            return base.Channel.DeleteMeetingAsync(t);
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Meeting> ReadAllMeeting() {
            return base.Channel.ReadAllMeeting();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Meeting>> ReadAllMeetingAsync() {
            return base.Channel.ReadAllMeetingAsync();
        }
        
        public BookAnArtisanMVC.ServiceReference.Meeting AddUserToMeeting(BookAnArtisanMVC.ServiceReference.Meeting m, BookAnArtisanMVC.ServiceReference.User u) {
            return base.Channel.AddUserToMeeting(m, u);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Meeting> AddUserToMeetingAsync(BookAnArtisanMVC.ServiceReference.Meeting m, BookAnArtisanMVC.ServiceReference.User u) {
            return base.Channel.AddUserToMeetingAsync(m, u);
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Meeting> ReadAllForUser(BookAnArtisanMVC.ServiceReference.User user) {
            return base.Channel.ReadAllForUser(user);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Meeting>> ReadAllForUserAsync(BookAnArtisanMVC.ServiceReference.User user) {
            return base.Channel.ReadAllForUserAsync(user);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IProjectService")]
    public interface IProjectService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/CreateProject", ReplyAction="http://tempuri.org/IProjectService/CreateProjectResponse")]
        BookAnArtisanMVC.ServiceReference.Project CreateProject(BookAnArtisanMVC.ServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/CreateProject", ReplyAction="http://tempuri.org/IProjectService/CreateProjectResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Project> CreateProjectAsync(BookAnArtisanMVC.ServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/ReadProject", ReplyAction="http://tempuri.org/IProjectService/ReadProjectResponse")]
        BookAnArtisanMVC.ServiceReference.Project ReadProject(BookAnArtisanMVC.ServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/ReadProject", ReplyAction="http://tempuri.org/IProjectService/ReadProjectResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Project> ReadProjectAsync(BookAnArtisanMVC.ServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/UpdateProject", ReplyAction="http://tempuri.org/IProjectService/UpdateProjectResponse")]
        BookAnArtisanMVC.ServiceReference.Project UpdateProject(BookAnArtisanMVC.ServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/UpdateProject", ReplyAction="http://tempuri.org/IProjectService/UpdateProjectResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Project> UpdateProjectAsync(BookAnArtisanMVC.ServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/DeleteProject", ReplyAction="http://tempuri.org/IProjectService/DeleteProjectResponse")]
        BookAnArtisanMVC.ServiceReference.Project DeleteProject(BookAnArtisanMVC.ServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/DeleteProject", ReplyAction="http://tempuri.org/IProjectService/DeleteProjectResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Project> DeleteProjectAsync(BookAnArtisanMVC.ServiceReference.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/ReadAllProject", ReplyAction="http://tempuri.org/IProjectService/ReadAllProjectResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project> ReadAllProject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/ReadAllProject", ReplyAction="http://tempuri.org/IProjectService/ReadAllProjectResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project>> ReadAllProjectAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectServiceChannel : BookAnArtisanMVC.ServiceReference.IProjectService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectServiceClient : System.ServiceModel.ClientBase<BookAnArtisanMVC.ServiceReference.IProjectService>, BookAnArtisanMVC.ServiceReference.IProjectService {
        
        public ProjectServiceClient() {
        }
        
        public ProjectServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookAnArtisanMVC.ServiceReference.Project CreateProject(BookAnArtisanMVC.ServiceReference.Project t) {
            return base.Channel.CreateProject(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Project> CreateProjectAsync(BookAnArtisanMVC.ServiceReference.Project t) {
            return base.Channel.CreateProjectAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Project ReadProject(BookAnArtisanMVC.ServiceReference.Project t) {
            return base.Channel.ReadProject(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Project> ReadProjectAsync(BookAnArtisanMVC.ServiceReference.Project t) {
            return base.Channel.ReadProjectAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Project UpdateProject(BookAnArtisanMVC.ServiceReference.Project t) {
            return base.Channel.UpdateProject(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Project> UpdateProjectAsync(BookAnArtisanMVC.ServiceReference.Project t) {
            return base.Channel.UpdateProjectAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Project DeleteProject(BookAnArtisanMVC.ServiceReference.Project t) {
            return base.Channel.DeleteProject(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Project> DeleteProjectAsync(BookAnArtisanMVC.ServiceReference.Project t) {
            return base.Channel.DeleteProjectAsync(t);
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project> ReadAllProject() {
            return base.Channel.ReadAllProject();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project>> ReadAllProjectAsync() {
            return base.Channel.ReadAllProjectAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRentingService")]
    public interface IRentingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentingService/CreateBooking", ReplyAction="http://tempuri.org/IRentingService/CreateBookingResponse")]
        BookAnArtisanMVC.ServiceReference.Booking CreateBooking(BookAnArtisanMVC.ServiceReference.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentingService/CreateBooking", ReplyAction="http://tempuri.org/IRentingService/CreateBookingResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Booking> CreateBookingAsync(BookAnArtisanMVC.ServiceReference.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentingService/ReadBooking", ReplyAction="http://tempuri.org/IRentingService/ReadBookingResponse")]
        BookAnArtisanMVC.ServiceReference.Booking ReadBooking(BookAnArtisanMVC.ServiceReference.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentingService/ReadBooking", ReplyAction="http://tempuri.org/IRentingService/ReadBookingResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Booking> ReadBookingAsync(BookAnArtisanMVC.ServiceReference.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentingService/UpdateBooking", ReplyAction="http://tempuri.org/IRentingService/UpdateBookingResponse")]
        BookAnArtisanMVC.ServiceReference.Booking UpdateBooking(BookAnArtisanMVC.ServiceReference.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentingService/UpdateBooking", ReplyAction="http://tempuri.org/IRentingService/UpdateBookingResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Booking> UpdateBookingAsync(BookAnArtisanMVC.ServiceReference.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentingService/DeleteBooking", ReplyAction="http://tempuri.org/IRentingService/DeleteBookingResponse")]
        BookAnArtisanMVC.ServiceReference.Booking DeleteBooking(BookAnArtisanMVC.ServiceReference.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentingService/DeleteBooking", ReplyAction="http://tempuri.org/IRentingService/DeleteBookingResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Booking> DeleteBookingAsync(BookAnArtisanMVC.ServiceReference.Booking t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentingService/ReadAllBooking", ReplyAction="http://tempuri.org/IRentingService/ReadAllBookingResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Booking> ReadAllBooking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentingService/ReadAllBooking", ReplyAction="http://tempuri.org/IRentingService/ReadAllBookingResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Booking>> ReadAllBookingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentingServiceChannel : BookAnArtisanMVC.ServiceReference.IRentingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentingServiceClient : System.ServiceModel.ClientBase<BookAnArtisanMVC.ServiceReference.IRentingService>, BookAnArtisanMVC.ServiceReference.IRentingService {
        
        public RentingServiceClient() {
        }
        
        public RentingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookAnArtisanMVC.ServiceReference.Booking CreateBooking(BookAnArtisanMVC.ServiceReference.Booking t) {
            return base.Channel.CreateBooking(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Booking> CreateBookingAsync(BookAnArtisanMVC.ServiceReference.Booking t) {
            return base.Channel.CreateBookingAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Booking ReadBooking(BookAnArtisanMVC.ServiceReference.Booking t) {
            return base.Channel.ReadBooking(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Booking> ReadBookingAsync(BookAnArtisanMVC.ServiceReference.Booking t) {
            return base.Channel.ReadBookingAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Booking UpdateBooking(BookAnArtisanMVC.ServiceReference.Booking t) {
            return base.Channel.UpdateBooking(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Booking> UpdateBookingAsync(BookAnArtisanMVC.ServiceReference.Booking t) {
            return base.Channel.UpdateBookingAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.Booking DeleteBooking(BookAnArtisanMVC.ServiceReference.Booking t) {
            return base.Channel.DeleteBooking(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.Booking> DeleteBookingAsync(BookAnArtisanMVC.ServiceReference.Booking t) {
            return base.Channel.DeleteBookingAsync(t);
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Booking> ReadAllBooking() {
            return base.Channel.ReadAllBooking();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Booking>> ReadAllBookingAsync() {
            return base.Channel.ReadAllBookingAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateUser", ReplyAction="http://tempuri.org/IUserService/CreateUserResponse")]
        BookAnArtisanMVC.ServiceReference.User CreateUser(BookAnArtisanMVC.ServiceReference.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/CreateUser", ReplyAction="http://tempuri.org/IUserService/CreateUserResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.User> CreateUserAsync(BookAnArtisanMVC.ServiceReference.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ReadUser", ReplyAction="http://tempuri.org/IUserService/ReadUserResponse")]
        BookAnArtisanMVC.ServiceReference.User ReadUser(BookAnArtisanMVC.ServiceReference.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ReadUser", ReplyAction="http://tempuri.org/IUserService/ReadUserResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.User> ReadUserAsync(BookAnArtisanMVC.ServiceReference.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        BookAnArtisanMVC.ServiceReference.User UpdateUser(BookAnArtisanMVC.ServiceReference.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.User> UpdateUserAsync(BookAnArtisanMVC.ServiceReference.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        BookAnArtisanMVC.ServiceReference.User DeleteUser(BookAnArtisanMVC.ServiceReference.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.User> DeleteUserAsync(BookAnArtisanMVC.ServiceReference.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ReadAllUser", ReplyAction="http://tempuri.org/IUserService/ReadAllUserResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.User> ReadAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ReadAllUser", ReplyAction="http://tempuri.org/IUserService/ReadAllUserResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.User>> ReadAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchByName", ReplyAction="http://tempuri.org/IUserService/SearchByNameResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.User> SearchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SearchByName", ReplyAction="http://tempuri.org/IUserService/SearchByNameResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.User>> SearchByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : BookAnArtisanMVC.ServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<BookAnArtisanMVC.ServiceReference.IUserService>, BookAnArtisanMVC.ServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookAnArtisanMVC.ServiceReference.User CreateUser(BookAnArtisanMVC.ServiceReference.User t) {
            return base.Channel.CreateUser(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.User> CreateUserAsync(BookAnArtisanMVC.ServiceReference.User t) {
            return base.Channel.CreateUserAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.User ReadUser(BookAnArtisanMVC.ServiceReference.User t) {
            return base.Channel.ReadUser(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.User> ReadUserAsync(BookAnArtisanMVC.ServiceReference.User t) {
            return base.Channel.ReadUserAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.User UpdateUser(BookAnArtisanMVC.ServiceReference.User t) {
            return base.Channel.UpdateUser(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.User> UpdateUserAsync(BookAnArtisanMVC.ServiceReference.User t) {
            return base.Channel.UpdateUserAsync(t);
        }
        
        public BookAnArtisanMVC.ServiceReference.User DeleteUser(BookAnArtisanMVC.ServiceReference.User t) {
            return base.Channel.DeleteUser(t);
        }
        
        public System.Threading.Tasks.Task<BookAnArtisanMVC.ServiceReference.User> DeleteUserAsync(BookAnArtisanMVC.ServiceReference.User t) {
            return base.Channel.DeleteUserAsync(t);
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.User> ReadAllUser() {
            return base.Channel.ReadAllUser();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.User>> ReadAllUserAsync() {
            return base.Channel.ReadAllUserAsync();
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.User> SearchByName(string name) {
            return base.Channel.SearchByName(name);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.User>> SearchByNameAsync(string name) {
            return base.Channel.SearchByNameAsync(name);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IProjectSearch")]
    public interface IProjectSearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectSearch/SearchByTag", ReplyAction="http://tempuri.org/IProjectSearch/SearchByTagResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project> SearchByTag(string search_tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectSearch/SearchByTag", ReplyAction="http://tempuri.org/IProjectSearch/SearchByTagResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project>> SearchByTagAsync(string search_tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectSearch/SearchByProjectUser", ReplyAction="http://tempuri.org/IProjectSearch/SearchByProjectUserResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project> SearchByProjectUser(BookAnArtisanMVC.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectSearch/SearchByProjectUser", ReplyAction="http://tempuri.org/IProjectSearch/SearchByProjectUserResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project>> SearchByProjectUserAsync(BookAnArtisanMVC.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectSearch/SearchByProjectAddress", ReplyAction="http://tempuri.org/IProjectSearch/SearchByProjectAddressResponse")]
        System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project> SearchByProjectAddress(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectSearch/SearchByProjectAddress", ReplyAction="http://tempuri.org/IProjectSearch/SearchByProjectAddressResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project>> SearchByProjectAddressAsync(string address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectSearchChannel : BookAnArtisanMVC.ServiceReference.IProjectSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectSearchClient : System.ServiceModel.ClientBase<BookAnArtisanMVC.ServiceReference.IProjectSearch>, BookAnArtisanMVC.ServiceReference.IProjectSearch {
        
        public ProjectSearchClient() {
        }
        
        public ProjectSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project> SearchByTag(string search_tag) {
            return base.Channel.SearchByTag(search_tag);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project>> SearchByTagAsync(string search_tag) {
            return base.Channel.SearchByTagAsync(search_tag);
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project> SearchByProjectUser(BookAnArtisanMVC.ServiceReference.User user) {
            return base.Channel.SearchByProjectUser(user);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project>> SearchByProjectUserAsync(BookAnArtisanMVC.ServiceReference.User user) {
            return base.Channel.SearchByProjectUserAsync(user);
        }
        
        public System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project> SearchByProjectAddress(string address) {
            return base.Channel.SearchByProjectAddress(address);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookAnArtisanMVC.ServiceReference.Project>> SearchByProjectAddressAsync(string address) {
            return base.Channel.SearchByProjectAddressAsync(address);
        }
    }
}
